FROM ubuntu:20.04

# Useful labels
LABEL version="0.0.1"
LABEL maintainersNames="Camila Morais"

# Variables
ARG ENV=dev
ARG PYTHON_VERSION=3.9
ARG DEBIAN_FRONTEND=noninteractive

# Installing APT packages and more
RUN apt update \
&& apt install -y nano \
&& apt install -y curl \
&& apt install -y wget \
&& apt install -y zip \
&& apt install -y cron \
&& apt install -y systemd \
&& apt install -y python${PYTHON_VERSION} \
&& apt install -y python3-pip \
&& apt install -y openjdk-8-jdk \
&& apt install -y build-essential python3-dev python2.7-dev libldap2-dev libsasl2-dev slapd ldap-utils tox lcov valgrind \
&& apt clean

# Setting up Java and Spark configurations & Environment Variables
RUN echo "JAVA_HOME=$(which java)" >> ~/.bashrc \
&& echo "export SPARK_LOCAL_IP="0.0.0.0"" >> ~/.bashrc \
&& echo "export ENV=${ENV}" >> ~/.bashrc \
&& echo "export PYTHONPATH=/root/projetos/utils" >> ~/.bashrc \
&& echo "export PATH=$PATH:/root/projetos/scripts" >> ~/.bashrc \
&& echo "export NODE=${NODE}" >> ~/.bashrc \
&& . ~/.bashrc

# Installing Python libraries
RUN pip3 install pyspark==3.2.0 \
&& pip3 install numpy==1.21.2 \
&& pip3 install pandas==1.3.4 \
&& pip3 install arrow==1.2.0 \
&& pip3 install boto3==1.18.63 \
&& pip3 install jupyterlab==3.2.0 \
&& pip3 install quinn==0.9.0 \
&& pip3 install click==8.0.3 \
&& pip3 install pyarrow==6.0.1 \
&& pip3 install fsspec==2021.11.1 \
&& pip3 install s3fs==2021.11.1 \
&& pip3 install pg8000==1.24.0 \
&& pip3 install requests==2.27.1 \
&& pip3 install python-ldap==3.4.0 \
&& pip3 install pyathenajdbc==3.0.1 \
&& pip3 install ldap3==2.9.1 \
&& pip3 install awswrangler==2.14.0 \
&& pip3 install paramiko==2.11.0 \
&& pip3 install redshift-connector==2.0.907 \
&& pip3 install twilio==7.3.1 \
&& pip3 install joblib==1.1.0 \
&& pip3 install tableauserverclient==0.19.0 \
&& pip3 install python-twitter==3.5

# Setting up Jupyter Lab configuration file
RUN jupyter-lab --generate-config \
&& echo "c.ServerApp.ip = '0.0.0.0'" >> ~/.jupyter/jupyter_lab_config.py \
&& echo "c.ServerApp.port = 8888" >> ~/.jupyter/jupyter_lab_config.py \
&& echo "c.ServerApp.allow_origin = '*'" >> ~/.jupyter/jupyter_lab_config.py \
&& echo "c.ServerApp.allow_root = True" >> ~/.jupyter/jupyter_lab_config.py \
&& echo "c.ServerApp.open_browser = False" >> ~/.jupyter/jupyter_lab_config.py

# Create shared directory with host
RUN mkdir /root/projetos/ \
#&& mkdir /root/.aws \
#&& mkdir /root/logs

# Copy hello-cron file to the cron.d directory
#COPY crontab_container.txt /etc/cron.d/crontab_container.txt

# Give execution rights on the cron job and apply cron job
#RUN chmod 0644 /etc/cron.d/crontab_container.txt \
#&& crontab /etc/cron.d/crontab_container.txt

# Landing in "/root/" diretory by Root user
USER root
WORKDIR "/root/"

# Starting cron service

CMD ["cron", "-f"]

# Landing in Bash application
ENTRYPOINT ["/bin/bash"]

# Expose ports for services (Jupyter Lab and Spark UI)
EXPOSE 8888 4040